### ISSUE TITLE
Feature request: remember scroll position when switching editors

### ISSUE THREAD

**Issue by lzambarda** [kohii/smoothcsv3#11]
With multiple editors open it would be great to be able to switch between them and having the view in the same position it was left at.

**Comment by kohii** [comment]
Thank you for reporting this.
The feature was already intended to behave this way, but a bug prevented it from working correctly.
A fix has been implemented and will be included in the next release.

**Comment by kohii** [comment]
This bug is fixed in [v3.0.0-beta.3](https://github.com/kohii/smoothcsv3/releases/tag/v3.0.0-beta.3)!
