### ISSUE TITLE
【機能要望】csvのセパレーターを変更できる機能

### ISSUE THREAD

**Issue by Odashikonbu** [kohii/smoothcsv3#7]
こんにちは！SmoothCSV3も愛用させていただいています！
相談なのですが、csvのセパレーター(デフォルトだとカンマ区切り)を変更する機能を追加していただく事は可能でしょうか？
私はたまにゲームのmodの翻訳作業でcsvを扱っているのですが、使われているcsvはセパレーターに|やセミコロンを使用している物も多いため、それらの形式に対応できると非常に助かります。

**Comment by kohii** [comment]
ご要望ありがとうございます！

v3 ではファイルを開くときに区切り文字を指定する機能はまだ実装していませんが、ファイルを開いたあとに区切り文字を変更できるようにはなっています。

![CleanShot 2024-12-02 at 09 54 01@2x](https://github.com/user-attachments/assets/5f96a03c-6cd2-4a7a-95d1-c495a9b3904a)

- 画面下部のステータスバー「区切り文字」あたりをクリックするか、コマンドパレットから「Chage File Format」を選ぶことでこのダイアログが表示されます。
- `|` は未対応なので、任意の文字を入れられるように改修したいと思います。

また、SmoothCSV はファイルを開くときに区切り文字を自動判定しますが、現状ではこれらの文字は未対応です。
できれば自動判定できるようにしたいと思うのですが、区切り文字が `;` や `|` であることはファイルの拡張子から推測可能でしょうか？

**Comment by Odashikonbu** [comment]
残念ながらja.csvのようなよくある名前のcsvファイルなので中身以外では推測出来ないと思います。
ただ|を区切り文字にしているのはウィッチャー3の翻訳だけですし、レアケース中のレアケースなのでわざわざ自動判別まで対応していただくまでもないかと。

**Comment by kohii** [comment]
[v3.0.0-beta.3](https://github.com/kohii/smoothcsv3/releases/tag/v3.0.0-beta.3) で対応しました！
区切り文字の自動判定で `;` や `|` にも対応しています。
